### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by palexdev** [dustinkredmond/FXTrayIcon#45]
It appears the application hangs indefinitely on this line of code: [FXTrayIcon](https://github.com/dustinkredmond/FXTrayIcon/blob/112bd07256ba93df8bb9650b5f8e5a0a19dbd5fa/src/main/java/com/dustinredmond/fxtrayicon/FXTrayIcon.java#L197)

Edit: Wrapping the icon instantiation and show in a SwingUtilities.invokeLater seems to fix the issue but the icon in the tray in just a black rectangle. But this is probably fault of GNOME for not having tray support natively (needs shell extension)

**Comment by dustinkredmond** [comment]
@palexdev there are some known compatibility issues with certain Linux desktop environments. Can you please send the specs of your current setup?

I could have sworn at one point that I had this library working on a test VM with GNOME as the desktop environment.

**Comment by palexdev** [comment]
> @palexdev there are some known compatibility issues with certain Linux desktop environments. Can you please send the specs of your current setup?
> 
> I could have sworn at one point that I had this library working on a test VM with GNOME as the desktop environment.

Of course, what do you need exactly?

**Comment by dustinkredmond** [comment]
Linux Distribution/version, and version of GNOME if you could, please.

**Comment by palexdev** [comment]
OS: Garuda Linux x86_64
Kernel: 5.16
DE: GNOME 41.4
Full info from neofetch: [Screenshot](https://user-images.githubusercontent.com/16880178/155620450-b54c7b4d-5c8b-44d9-8376-74166d2a6225.png)

**Comment by dustinkredmond** [comment]
@palexdev I will check further this weekend. Most folks don't even get to the black rectangle on GNOME, as I've seen in the past. I'm assuming that `FXTrayIcon.isTrayIconSupported()` returns `true`?

**Comment by palexdev** [comment]
@dustinkredmond any news on this?

**Comment by dustinkredmond** [comment]
@palexdev I apologize for the delay, as I'm in the process of moving and still don't have internet at my new residence. Since you're using an extension to GNOME that causes the library to return `true`, I'm not sure how best to handle this.

Unfortunately, I don't think we can support this due to the limitations imposed by AWT. I haven't found an acceptable workaround, so ideally FXTrayIcon's `isSupported` should return `false`. I hate to hardcode a return of `false` in the event that someone is using the same platform/extensions that you are, but I also hate that it returns `true` when it's ultimately not supported.

Let me get the other maintainers' opinions on how best to handle this. I definitely don't want the library hanging up an application because of an incorrect return value from `isSupported`.

**Comment by dustinkredmond** [comment]
I'm happy to leave this issue open if folks want to further explore possibilities for a fix. Ultimately, FXTrayIcon is (and always has been) nothing more than an abstraction over the AWT API. This really limits the possibilities we have for improvement, as we rely on the underlying implementation to be solid. If you all want to explore this further, please use this Issue to further discuss, otherwise, please close if you deem relevant. Thanks all for your contributions!

**Comment by EasyG0ing1** [comment]
@dustinkredmond - Since I'm more of a "use if arm twisted" - style of Linux user, I have no interest in devoting large amounts of time to further its cause ... JavaFX doesn't seem to be particularly welcome much anywhere in the Linux space from what I gathered with the time I spent looking into the issues. I don't usually - as a rule - go where I'm not welcome. ☺

**Comment by EasyG0ing1** [comment]
@dustinkredmond 

> @palexdev I will check further this weekend. Most folks don't even get to the black rectangle on GNOME, as I've seen in the past. I'm assuming that FXTrayIcon.isTrayIconSupported() returns true?

As I've been testing GistFX on Linux (Ubuntu latest version) I've been noticing that FXT returns true on the supported test, but it ends up hanging the application so I just coded FXT out of the app if Linux is running, just to safe.

**Comment by dustinkredmond** [comment]
Closing issue, preferring to keep discourse on #12 which addresses attempts to get the library working on Linux in general.
