### ISSUE TITLE
MenuItem order wrong for .addExitMenuItem()

### ISSUE THREAD

**Issue by azplanlos** [dustinkredmond/FXTrayIcon#50]
When building a Tray Icon using the Builder API and adding .addExitMenuItem() the exit menu item shows up on top of the list.

Check:

    FXTrayIcon trayIcon =
                new FXTrayIcon.Builder(stage, resource).menuItem("Settings",
                        e-> myMethod()).separator().menuItem(item).addExitMenuItem().show().build();

**Comment by EasyG0ing1** [comment]
@azplanlos - Yeah, this is been fixed in pull request #47 which has been merged, but not published yet...

Heres a screen shot from that PR: 

<img width="810" alt="Screen Shot 2022-05-11 at 2 47 58 AM" src="https://user-images.githubusercontent.com/10106834/167821986-0db37a7e-ddb3-4988-bb57-9f4dd034842b.png">

**Comment by dustinkredmond** [comment]
Closing this as @EasyG0ing1's commit fixed this. I've just been too busy to publish a release. I will publish the next release with this fix later this evening. Thank you both for bringing this to my attention.
