### ISSUE TITLE
After adding checkMenuItem, chech or uncheck not working 

### ISSUE THREAD

**Issue by ctoabidmaqbool** [dustinkredmond/FXTrayIcon#65]
After adding checkMenuItem check / uncheck change listener not working fine.

e.g. not working fine:
```
CheckMenuItem checkMenu1 = new CheckMenuItem("Test");

trayIcon.addMenuItem(checkMenu1);

checkMenu1.setSelected(true);
```

**Comment by dustinkredmond** [comment]
Working on this with commit 887be5c, fill be fixed before next minor version release.

**Comment by ctoabidmaqbool** [comment]
@dustinkredmond Please re-open this issue, this it's not 100% working!

below is the simple example!

```
import com.dustinredmond.fxtrayicon.FXTrayIcon;
import javafx.application.Application;
import javafx.scene.control.CheckMenuItem;
import javafx.stage.Stage;

import java.util.Objects;

public class TrayIconDemo extends Application {

    private CheckMenuItem mnuAutoBackup;

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("FXTrayIcon Demo");

        // Create FXTrayIcon
        FXTrayIcon trayIcon = new FXTrayIcon(primaryStage, Objects.requireNonNull(getClass().getResource("/icon.png")));
        trayIcon.show();

        // Create CheckMenuItem
        mnuAutoBackup = new CheckMenuItem("Auto Backup");
        mnuAutoBackup.setOnAction(this::mnuAutoBackupOnAction);

        // Add menu item to tray icon
        trayIcon.addMenuItem(mnuAutoBackup);

        primaryStage.setIconified(true); // Hide window on startup
    }

    private void mnuAutoBackupOnAction(javafx.event.ActionEvent e) {
        // Fix: Manually toggle the CheckMenuItem state
        mnuAutoBackup.setSelected(!mnuAutoBackup.isSelected());

        // Print the state
        System.out.println("AutoBackup selected: " + mnuAutoBackup.isSelected());
    }

    public static void main(String[] args) {
        launch(args);
    }
}

```

without, this line e.g. `mnuAutoBackup.setSelected(!mnuAutoBackup.isSelected());` it's not working as expacted,

**Comment by EasyG0ing1** [comment]
@ctoabidmaqbool 

Hi, 

The problem was in the AWTUtils class. I fixed the bug and created a [Pull Request](https://github.com/dustinkredmond/FXTrayIcon/pull/92). However, if you unzip this file into your Maven folder `.m2/repository/com/dustinredmond/fxtrayicon/FXTrayIcon` you can simply change the version in your POM file to `4.2.2-ISSUE65` and you should be good to go. 

When Dustin publishes the next version update to the Maven repo, you can just start using that version instead.

I tested the updated library using your code without the manual fix `mnuAutoBackup.setSelected(!mnuAutoBackup.isSelected());` and it properly reported the state of the check menu item each time it was toggled.

Mike

[FXTrayIcon-4.2.2-ISSUE65.zip](https://github.com/user-attachments/files/19639263/FXTrayIcon-4.2.2-ISSUE65.zip)
